[package]
name = "rust-bookstor-api"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version = "^0.5" , features = ["json"]}
sea-orm = { version = "^1.1" , features = [
    "sqlx-mysql",
    "runtime-async-std-native-tls",
    "macros",
]}
sea-orm-migration = "^1.1"